// SIGN UP TYPES
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";

// SIGN IN TYPES
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_ERROR = "SIGNIN_ERROR";
export const SIGNIN_VERIFICATION = "SIGNIN_VERIFICATION";

//SIGN OUT
export const SIGN_OUT_SUCCES = "SIGN_OUT_SUCCES";
export const SIGN_OUT_FAILED = "SIGN_OUT_FAILED";